// Code from AOACN.pdf of page 39(57/794).
// Code list: 1-10
//   Can not catch exception.

program testBadInput4;
#include("stdlib.hhf");

static input: int32;

begin testBadInput4;

	// This forever loop repeats until the user enters
	// a good integer and the BREAK statement below
	// exists the loop.
	forever

		try
			stdout.put("Enter an integer value:");
			stdin.get(input);
			stdout.put("The first input value was:", input, nl);
			break;	// Notice
		exception(ex.ValueOutOfRange)
			stdout.put("The value was too large, reenter.", nl);
		exception(ex.ConversionError)
			stdout.put("The input contained illegal character, reenter.", nl);
		endtry;

	endfor;

	// Note that the following code is outside the loop and there
	// is no TRY...ENDTRY statement protecting this code.
	stdout.put("Enter another number:");
	stdin.get(input);
	stdout.put("The new number is:", input, nl);

end testBadInput4;
